<template>
<div class="analytics" v-loading="loading">
 <el-card><template #header><b>考勤统计分析</b></template>
 <div class="filters"><el-select v-model="courseId" @change="className='';load()" placeholder="课程"><el-option v-for="c in courses" :key="c.id" :label="c.courseName" :value="c.id"/></el-select><el-select v-model="className" clearable placeholder="全部班级" @change="load"><el-option v-for="c in stats.classes||[]" :key="c" :value="c" :label="c"/></el-select><el-input v-model="student" placeholder="姓名 / 学号" clearable @keyup.enter="load" @clear="load"/><el-date-picker v-model="dates" type="daterange" value-format="YYYY-MM-DD" @change="load" :shortcuts="shortcuts"/><el-button @click="load">查询</el-button><el-button type="primary" :disabled="!filtered.length || loading || queryDirty" :loading="exporting" @click="download">导出 Excel</el-button></div>
 <el-alert class="tip" :closable="false" title="已产生的考勤记录会实时纳入统计；未结束的考勤不会提前将未签到学生记为缺勤。出勤率＝（正常＋迟到）÷（正常＋迟到＋缺勤），已批准请假不计入分母。"/>
 <div class="cards"><div v-for="c in cards" :key="c.label"><span>{{c.label}}</span><strong>{{c.value}}</strong></div></div></el-card>
 <div class="charts"><el-card v-for="(title,i) in ['考勤状态占比','学生出勤率排名','出勤率变化']" :key="title"><h3>{{title}}</h3><el-select v-if="i===2" v-model="granularity" size="small" style="width:100px"><el-option label="按日" value="day"/><el-option label="按周" value="week"/><el-option label="按月" value="month"/></el-select><div :ref="el=>chartElements[i]=el" class="chart"/></el-card></div>
 <el-card><template #header><b>学生考勤明细</b></template><div class="filters"><el-checkbox v-model="onlyAbnormal">仅查看异常学生</el-checkbox><span>出勤率低于</span><el-input-number v-model="threshold" :min="0" :max="100" :controls="false"/><span>%，或有缺勤，或迟到至少</span><el-input-number v-model="lateThreshold" :min="1" :max="999" :controls="false"/><span>次</span></div>
 <el-table :data="paged" @sort-change="changeSort" :default-sort="{prop:'attendanceRate',order:'descending'}"><el-table-column prop="rank" label="排名" width="75"/><el-table-column prop="name" label="姓名" sortable="custom" min-width="100"/><el-table-column prop="studentNumber" label="学号" sortable="custom" min-width="120"/><el-table-column prop="className" label="班级" min-width="100"/><el-table-column v-for="c in counts" :key="c.key" :prop="c.key" :label="c.label" sortable="custom" width="95"/><el-table-column prop="attendanceRate" label="出勤率" sortable="custom" width="110"><template #default="{row}">{{rate(row.attendanceRate)}}</template></el-table-column><el-table-column label="异常原因" min-width="180"><template #default="{row}">{{reasons(row).join('；')||'—'}}</template></el-table-column><el-table-column label="详情" width="80"><template #default="{row}"><el-button link type="primary" @click="detail=row">查看</el-button></template></el-table-column></el-table>
 <el-pagination v-model:current-page="page" :page-size="20" :total="filtered.length" layout="total,prev,pager,next"/></el-card>
 <el-dialog :model-value="!!detail" @close="detail=null" title="学生考勤详情" width="min(520px,94vw)"><template v-if="detail"><p>{{detail.name}} · {{detail.studentNumber}} · {{detail.className}}</p><p>统计范围：{{dates?.join(' 至 ')||'全部日期'}}</p><p v-for="c in counts" :key="c.key">{{c.label}}：{{detail[c.key]}} 次</p><p>出勤率：{{rate(detail.attendanceRate)}}</p></template></el-dialog>
</div>
</template>
<script setup>
import {ref,computed,watch,onMounted,onUnmounted,nextTick} from 'vue'
import {ElMessage} from 'element-plus'
import {init,use} from 'echarts/core'
import {PieChart,BarChart,LineChart} from 'echarts/charts'
import {GridComponent,TooltipComponent,TitleComponent,LegendComponent,DataZoomComponent} from 'echarts/components'
import {CanvasRenderer} from 'echarts/renderers'
use([PieChart,BarChart,LineChart,GridComponent,TooltipComponent,TitleComponent,LegendComponent,DataZoomComponent,CanvasRenderer])
import dayjs from 'dayjs'
import {getCourseList} from '@/api/course'
import {getAttendanceStatistics,exportAttendance} from '@/api/attendance'
import {useUserStore} from '@/stores/user'
const user=useUserStore(),courses=ref([]),courseId=ref(null),className=ref(''),student=ref(''),stats=ref({}),applied=ref(null),loading=ref(false),exporting=ref(false),detail=ref(null)
const dates=ref([dayjs().startOf('month').format('YYYY-MM-DD'),dayjs().format('YYYY-MM-DD')]),shortcuts=[{text:'本月',value:()=>[dayjs().startOf('month').toDate(),new Date()]},{text:'本学期（2月/9月起）',value:()=>{const now=dayjs(),month=now.month();return [now.year(month===0?now.year()-1:now.year()).month(month===0||month>=8?8:1).startOf('month').toDate(),new Date()]}},{text:'最近六个月',value:()=>[dayjs().subtract(6,'month').toDate(),new Date()]}]
const granularity=ref('day')
const onlyAbnormal=ref(false),threshold=ref(80),lateThreshold=ref(3),page=ref(1),sort=ref({prop:'attendanceRate',order:'descending'}),chartElements=[];let charts=[],observer,sequence=0
const counts=[{key:'present',label:'正常'},{key:'late',label:'迟到'},{key:'leave',label:'请假'},{key:'absent',label:'缺勤'}],rate=n=>n==null?'—':`${n}%`
const cards=computed(()=>[{label:'学生人数',value:stats.value.studentCount||0},{label:'汇总出勤率',value:rate(stats.value.attendanceRate)},{label:'迟到人次',value:stats.value.late||0},{label:'缺勤人次',value:stats.value.absent||0},{label:'请假人次',value:stats.value.leave||0}])
const reasons=r=>[r.attendanceRate!=null&&r.attendanceRate<threshold.value?'出勤率偏低':'',r.absent>0?'有缺勤记录':'',r.late>=lateThreshold.value?'迟到较多':''].filter(Boolean)
const ranked=computed(()=>{let last,rank=0;return [...(stats.value.students||[])].sort((a,b)=>(b.attendanceRate??-1)-(a.attendanceRate??-1)).map((r,i)=>{if(r.attendanceRate!==last)rank=i+1;last=r.attendanceRate;return {...r,rank:r.attendanceRate==null?'—':rank}})})
const filtered=computed(()=>ranked.value.filter(r=>!onlyAbnormal.value||reasons(r).length))
const sorted=computed(()=>[...filtered.value].sort((a,b)=>{const key=sort.value.prop||'attendanceRate',x=a[key],y=b[key];if(x==null)return y==null?0:1;if(y==null)return -1;return (typeof x==='number'?x-y:String(x).localeCompare(String(y),'zh-CN',{numeric:true}))*(sort.value.order==='ascending'?1:-1)}))
const paged=computed(()=>sorted.value.slice((page.value-1)*20,page.value*20)),params=()=>({startDate:dates.value?.[0],endDate:dates.value?.[1],className:className.value||undefined,student:student.value||undefined})
const queryDirty=computed(()=>JSON.stringify(applied.value)!==JSON.stringify({courseId:courseId.value,...params()}))
async function load(){if(!courseId.value)return;const id=++sequence,query={courseId:courseId.value,...params()};loading.value=true;try{const data=await getAttendanceStatistics(query.courseId,query);if(id===sequence){stats.value=data;applied.value=query;page.value=1}}catch(e){if(id===sequence)stats.value={};if(!e.messageShown)ElMessage.error(e.message||'加载失败')}finally{if(id===sequence)loading.value=false}}
function changeSort(s){sort.value=s;page.value=1}
async function download(){exporting.value=true;try{const blob=await exportAttendance({...applied.value,studentIds:filtered.value.map(r=>r.id).join(',')});if(blob.type.includes('json'))throw new Error(JSON.parse(await blob.text()).message||'导出失败');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`考勤表-${courseId.value}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);ElMessage.success('考勤表已导出')}catch(e){if(!e.messageShown)ElMessage.error(e.message||'导出失败')}finally{exporting.value=false}}
function render(){if(charts.length!==3)return;const common={color:['#22a06b','#eaaa08','#8f4a4f','#e45858'],title:stats.value.total?undefined:{text:'暂无考勤数据',left:'center',top:'center',textStyle:{fontSize:14,color:'#98a2b3'}}};charts[0].setOption({...common,tooltip:{trigger:'item'},legend:{bottom:0},series:[{type:'pie',radius:['35%','65%'],data:counts.map(c=>({name:c.label,value:stats.value[c.key]||0})),label:{formatter:'{b}: {c} ({d}%)'}}]},true);const ranking=ranked.value.filter(r=>r.attendanceRate!=null);charts[1].setOption({...common,tooltip:{trigger:'axis'},grid:{left:45,right:20,bottom:90},xAxis:{type:'category',data:ranking.map(r=>`${r.name}\n${r.studentNumber||''}`),axisLabel:{rotate:30}},yAxis:{max:100,axisLabel:{formatter:'{value}%'}},dataZoom:ranking.length>12?[{type:'slider',start:0,end:Math.min(100,1200/ranking.length)}]:[],series:[{type:'bar',data:ranking.map(r=>r.attendanceRate),itemStyle:{color:'#b12f35'}}]},true);const buckets=new Map();for(const row of stats.value.trend||[]){const d=dayjs(row.date);const key=granularity.value==='month'?d.format('YYYY-MM'):granularity.value==='week'?d.subtract((d.day()+6)%7,'day').format('YYYY-MM-DD'):row.date;const bucket=buckets.get(key)||{date:key,present:0,late:0,absent:0};bucket.present+=row.present;bucket.late+=row.late;bucket.absent+=row.absent;buckets.set(key,bucket)}const trend=[...buckets.values()].map(r=>({...r,attendanceRate:r.present+r.late+r.absent?Math.round((r.present+r.late)*1000/(r.present+r.late+r.absent))/10:null}));charts[2].setOption({...common,tooltip:{trigger:'axis'},grid:{left:45,right:20,bottom:45},xAxis:{type:'category',data:trend.map(r=>r.date)},yAxis:{max:100,axisLabel:{formatter:'{value}%'}},series:[{type:'line',connectNulls:false,data:trend.map(r=>r.attendanceRate),itemStyle:{color:'#22a06b'}}]},true)}
watch(granularity,render);watch(stats,async()=>{await nextTick();render()});watch([onlyAbnormal,threshold,lateThreshold],()=>page.value=1)
onMounted(async()=>{charts=chartElements.map(el=>init(el));observer=new ResizeObserver(()=>charts.forEach(c=>c.resize()));chartElements.forEach(el=>observer.observe(el));render();try{const query={page:1,size:100};if(user.isTeacher)query.teacherId=user.userInfo.id;courses.value=(await getCourseList(query))?.list||[];if(courses.value.length){courseId.value=courses.value[0].id;await load()}}catch(e){if(!e.messageShown)ElMessage.error('课程加载失败')}})
onUnmounted(()=>{sequence++;observer?.disconnect();charts.forEach(c=>c.dispose())})
</script>
<style scoped>
.analytics{display:grid;gap:18px;min-width:0}.filters{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:15px}.filters>.el-select,.filters>.el-input{width:170px}.filters .el-input-number{width:80px}.tip{margin:18px 0}.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.cards>div{padding:20px;background:#f5f8ff;border-radius:12px}.cards span{font-size:13px;color:#667085}.cards strong{display:block;font-size:28px;margin-top:12px;color:#263956}.charts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.chart{height:300px;width:100%}h3{font-size:15px;margin:0}.el-pagination{margin-top:18px;overflow:auto}@media(max-width:1100px){.charts{grid-template-columns:1fr}.cards{grid-template-columns:repeat(3,1fr)}}@media(max-width:600px){.cards{grid-template-columns:repeat(2,1fr)}.cards>div{padding:14px}.cards strong{font-size:24px}.filters :deep(.el-date-editor){max-width:100%}}
</style>
