<template><el-card><template #header><b>{{ userStore.isStudent ? '请假申请' : '请假审批' }}</b></template>
<el-form v-if="userStore.isStudent" :inline="true" :model="form"><el-form-item label="课程"><el-select v-model="form.courseId" style="width:180px"><el-option v-for="c in courses" :key="c.id" :label="c.courseName" :value="c.id" /></el-select></el-form-item><el-form-item label="请假日期"><el-date-picker v-model="form.leaveDate" value-format="YYYY-MM-DD" /></el-form-item><el-form-item label="原因"><el-input v-model="form.reason" maxlength="500" show-word-limit /></el-form-item><el-form-item><el-button type="primary" @click="submit">提交申请</el-button></el-form-item></el-form>
<el-table :data="rows" v-loading="loading"><el-table-column prop="studentNumber" label="学号"/><el-table-column prop="studentName" label="姓名"/><el-table-column prop="courseName" label="课程"/><el-table-column prop="leaveDate" label="日期"/><el-table-column prop="reason" label="原因" min-width="180"/><el-table-column label="状态"><template #default="{row}"><el-tag :type="tagType(row.status)">{{ statusName(row.status) }}</el-tag></template></el-table-column><el-table-column label="详情" width="80"><template #default="{row}"><el-button link type="primary" @click="detail=row">查看</el-button></template></el-table-column><el-table-column prop="reviewComment" label="审批意见"/><el-table-column v-if="!userStore.isStudent" label="操作" width="170"><template #default="{row}"><template v-if="row.status==='PENDING'"><el-button size="small" type="success" @click="review(row,true)">批准</el-button><el-button size="small" type="danger" @click="review(row,false)">驳回</el-button></template></template></el-table-column></el-table></el-card><el-dialog :model-value="!!detail" @close="detail=null" title="请假详情" width="min(600px,94vw)"><el-descriptions v-if="detail" :column="1" border><el-descriptions-item v-for="f in fields" :key="f.key" :label="f.label">{{f.key==='status'?statusName(detail.status):String(detail[f.key]??'—').replace('T',' ')}}</el-descriptions-item></el-descriptions></el-dialog></template>
<script setup>
import {ref,onMounted} from 'vue';import {ElMessage,ElMessageBox} from 'element-plus';import {useUserStore} from '@/stores/user';import {getEnrolledCourses} from '@/api/course';import {getLeaveRequests,submitLeave,reviewLeave} from '@/api/attendance';
const detail=ref(null),fields=[{key:'studentName',label:'姓名'},{key:'studentNumber',label:'学号'},{key:'courseName',label:'课程'},{key:'startTime',label:'请假开始时间'},{key:'endTime',label:'请假结束时间'},{key:'durationMinutes',label:'请假时长（分钟）'},{key:'reason',label:'原因'},{key:'createdAt',label:'申请时间'},{key:'status',label:'审批状态'},{key:'reviewerName',label:'审批教师'},{key:'reviewedAt',label:'审批时间'},{key:'reviewComment',label:'审批意见'}];
const userStore=useUserStore(),rows=ref([]),courses=ref([]),loading=ref(false),form=ref({courseId:null,leaveDate:'',reason:''});const statusName=s=>({PENDING:'待审批',APPROVED:'已批准',REJECTED:'已驳回'}[s]||s),tagType=s=>({PENDING:'warning',APPROVED:'success',REJECTED:'danger'}[s]||'info');
async function load(){loading.value=true;try{rows.value=await getLeaveRequests();if(userStore.isStudent)courses.value=await getEnrolledCourses()}finally{loading.value=false}}async function submit(){if(!form.value.courseId||!form.value.leaveDate||!form.value.reason.trim()){ElMessage.warning('请完整填写课程、日期和原因');return}await submitLeave(form.value);ElMessage.success('申请已提交');form.value={courseId:null,leaveDate:'',reason:''};load()}async function review(row,approved){let comment='';try{const r=await ElMessageBox.prompt(approved?'请输入审批意见（可留空）':'请输入驳回原因','审批确认',{inputValidator:v=>approved||!!v?.trim()||'驳回时必须填写原因'});comment=r.value}catch{return}await reviewLeave(row.id,approved,comment);ElMessage.success('审批完成');load()}onMounted(load)
</script>
