<template><el-card><template #header><div class="header"><div><b>课程小组管理</b><p>由老师分配成员并指定组长，组长可代本组成员进行考勤。</p></div><el-select v-model="courseId" placeholder="选择课程" @change="loadAll"><el-option v-for="c in courses" :key="c.id" :label="c.courseName" :value="c.id"/></el-select></div></template><el-empty v-if="!courseId" description="请先选择课程"/><template v-else><div class="toolbar"><el-button type="primary" @click="openCreate">新建小组</el-button><span>课程学生 {{students.length}} 人，小组 {{groups.length}} 个</span></div><el-collapse><el-collapse-item v-for="group in groups" :key="group.id" :name="group.id"><template #title><b>{{group.name}}</b><el-tag class="leader-tag" size="small">组长：{{leaderName(group)}}</el-tag></template><div class="group-actions"><el-select v-model="memberChoice[group.id]" filterable placeholder="选择未分组学生"><el-option v-for="s in availableStudents(group)" :key="s.id" :label="`${s.realName}（${s.studentId}）`" :value="s.id"/></el-select><el-button type="primary" plain @click="addMember(group)">添加成员</el-button><el-button type="danger" plain @click="removeGroup(group)">删除小组</el-button></div><el-table :data="group.members"><el-table-column prop="studentId" label="学号"/><el-table-column prop="realName" label="姓名"/><el-table-column label="身份"><template #default="{row}"><el-tag v-if="row.leader">组长</el-tag><span v-else>成员</span></template></el-table-column><el-table-column label="操作" width="180"><template #default="{row}"><el-button v-if="!row.leader" link type="primary" @click="makeLeader(group,row)">设为组长</el-button><el-button v-if="!row.leader" link type="danger" @click="removeMember(group,row)">移除</el-button></template></el-table-column></el-table></el-collapse-item></el-collapse><el-empty v-if="!groups.length" description="暂无小组，请新建"/></template><el-dialog v-model="dialog" title="新建课程小组" width="min(480px,94vw)"><el-form label-width="85px"><el-form-item label="小组名称"><el-input v-model="newName"/></el-form-item><el-form-item label="指定组长"><el-select v-model="newLeader" filterable style="width:100%"><el-option v-for="s in ungroupedStudents" :key="s.id" :label="`${s.realName}（${s.studentId}）`" :value="s.id"/></el-select></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="create">创建</el-button></template></el-dialog></el-card></template>
<script setup>
import {ref,reactive,computed,onMounted} from 'vue';import {ElMessage,ElMessageBox} from 'element-plus';import {getCourseList,getCourseStudents} from '@/api/course';import {getCourseGroups,createGroup,addGroupMember,removeGroupMember,setGroupLeader,deleteGroup} from '@/api/group'
const courses=ref([]),courseId=ref(null),students=ref([]),groups=ref([]),dialog=ref(false),newName=ref(''),newLeader=ref(null),memberChoice=reactive({})
const groupedIds=computed(()=>new Set(groups.value.flatMap(g=>g.members.map(m=>m.id))));const ungroupedStudents=computed(()=>students.value.filter(s=>!groupedIds.value.has(s.id)))
const leaderName=g=>g.members.find(m=>m.leader)?.realName||'未指定';const availableStudents=()=>ungroupedStudents.value
async function loadAll(){if(!courseId.value)return;[students.value,groups.value]=await Promise.all([getCourseStudents(courseId.value),getCourseGroups(courseId.value)])}
function openCreate(){newName.value='';newLeader.value=null;dialog.value=true}
async function create(){if(!newName.value.trim()||!newLeader.value)return ElMessage.warning('请填写小组名称并指定组长');await createGroup(courseId.value,newName.value.trim(),newLeader.value);dialog.value=false;await loadAll();ElMessage.success('小组已创建')}
async function addMember(g){const id=memberChoice[g.id];if(!id)return ElMessage.warning('请选择学生');await addGroupMember(g.id,id);memberChoice[g.id]=null;await loadAll()}
async function makeLeader(g,row){await setGroupLeader(g.id,row.id);await loadAll();ElMessage.success('组长已指定')}
async function removeMember(g,row){await ElMessageBox.confirm(`确定将 ${row.realName} 移出小组吗？`,'移除成员');await removeGroupMember(g.id,row.id);await loadAll()}
async function removeGroup(g){await ElMessageBox.confirm(`确定删除“${g.name}”吗？成员将变为未分组。`,'删除小组',{type:'warning'});await deleteGroup(g.id);await loadAll()}
onMounted(async()=>{const r=await getCourseList({page:1,size:200});courses.value=r?.list||[];if(courses.value.length){courseId.value=courses.value[0].id;await loadAll()}})
</script>
<style scoped>.header{display:flex;justify-content:space-between;align-items:center;gap:20px}.header p{margin:6px 0 0;color:#98a2b3;font-size:13px}.header .el-select{width:240px}.toolbar,.group-actions{display:flex;align-items:center;gap:10px;margin-bottom:16px}.toolbar{justify-content:space-between;color:#98a2b3}.group-actions .el-select{width:260px}.leader-tag{margin-left:12px}@media(max-width:650px){.header{align-items:flex-start;flex-direction:column}.header .el-select,.group-actions .el-select{width:100%}.group-actions{flex-wrap:wrap}}</style>
