CREATE TABLE IF NOT EXISTS user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  real_name VARCHAR(50) NOT NULL,
  student_id VARCHAR(20) UNIQUE,
  role VARCHAR(20) DEFAULT 'STUDENT',
  face_features CLOB,
  face_image_path VARCHAR(255),
  status TINYINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS course (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_name VARCHAR(100) NOT NULL,
  course_code VARCHAR(20) UNIQUE NOT NULL,
  teacher_id BIGINT NOT NULL,
  classroom VARCHAR(50),
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  week_day TINYINT NOT NULL,
  semester VARCHAR(20),
  max_students INT DEFAULT 100,
  status TINYINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_course_teacher FOREIGN KEY (teacher_id) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT NOT NULL,
  student_id BIGINT NOT NULL,
  attendance_date DATE NOT NULL,
  status VARCHAR(20) DEFAULT 'PRESENT',
  check_in_time TIMESTAMP,
  check_out_time TIMESTAMP,
  face_image VARCHAR(255),
  confidence DECIMAL(5,4),
  is_liveness TINYINT DEFAULT 0,
  location VARCHAR(100),
  device_info VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_attendance UNIQUE (course_id, student_id, attendance_date),
  CONSTRAINT fk_attendance_course FOREIGN KEY (course_id) REFERENCES course(id),
  CONSTRAINT fk_attendance_student FOREIGN KEY (student_id) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS student_course (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  course_id BIGINT NOT NULL,
  enroll_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status TINYINT DEFAULT 1,
  CONSTRAINT uk_student_course UNIQUE (student_id, course_id),
  CONSTRAINT fk_sc_student FOREIGN KEY (student_id) REFERENCES user(id),
  CONSTRAINT fk_sc_course FOREIGN KEY (course_id) REFERENCES course(id)
);

CREATE TABLE IF NOT EXISTS leave_request (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  course_id BIGINT NOT NULL,
  leave_date DATE NOT NULL,
  reason VARCHAR(500) NOT NULL,
  status VARCHAR(20) DEFAULT 'PENDING',
  reviewer_id BIGINT,
  review_comment VARCHAR(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  reviewed_at TIMESTAMP,
  CONSTRAINT uk_leave_request UNIQUE (student_id, course_id, leave_date),
  CONSTRAINT fk_leave_student FOREIGN KEY (student_id) REFERENCES user(id),
  CONSTRAINT fk_leave_course FOREIGN KEY (course_id) REFERENCES course(id)
);

CREATE TABLE IF NOT EXISTS student_group (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_name VARCHAR(50) NOT NULL,
  course_id BIGINT,
  leader_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_group_leader FOREIGN KEY (leader_id) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS student_group_member (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL,
  student_id BIGINT NOT NULL,
  joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_group_member UNIQUE (group_id, student_id),
  CONSTRAINT fk_group_member_group FOREIGN KEY (group_id) REFERENCES student_group(id),
  CONSTRAINT fk_group_member_student FOREIGN KEY (student_id) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS attendance_session (
 course_id BIGINT NOT NULL, attendance_date DATE NOT NULL, starts_at TIMESTAMP NOT NULL,
 ends_at TIMESTAMP NOT NULL, late_at TIMESTAMP, teacher_id BIGINT NOT NULL,
 settled BOOLEAN DEFAULT FALSE, PRIMARY KEY(course_id,attendance_date)
);
CREATE TABLE IF NOT EXISTS attendance_session_member (
 course_id BIGINT NOT NULL, attendance_date DATE NOT NULL, student_id BIGINT NOT NULL,
 PRIMARY KEY(course_id,attendance_date,student_id)
);

ALTER TABLE user ADD COLUMN IF NOT EXISTS class_name VARCHAR(80);
ALTER TABLE user ADD COLUMN IF NOT EXISTS face_reenroll_allowed BOOLEAN DEFAULT FALSE;
ALTER TABLE student_group ADD COLUMN IF NOT EXISTS course_id BIGINT;
-- Remove the legacy global uniqueness so one student can join one group per course.
ALTER TABLE student_group DROP CONSTRAINT IF EXISTS "CONSTRAINT_DC";
ALTER TABLE student_group_member DROP CONSTRAINT IF EXISTS "CONSTRAINT_F70";
ALTER TABLE leave_request ADD COLUMN IF NOT EXISTS start_time TIMESTAMP;
ALTER TABLE leave_request ADD COLUMN IF NOT EXISTS end_time TIMESTAMP;
CREATE TABLE IF NOT EXISTS attendance_audit (
 id VARCHAR(36) PRIMARY KEY, category VARCHAR(40) NOT NULL, entity_id BIGINT NOT NULL,
 before_status VARCHAR(30), after_status VARCHAR(30), operator_id BIGINT NOT NULL,
 reason VARCHAR(500), created_at TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS face_reenroll_request (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, student_id BIGINT NOT NULL,
 reason VARCHAR(500), status VARCHAR(20) DEFAULT 'PENDING', reviewer_id BIGINT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, reviewed_at TIMESTAMP
);
